version: '3.7'

services:

  redis:
    image: redis:5.0.3-alpine
    expose:
      - 6379

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
     - 6379:6379
     - 8001:8001
    expose:
      - 6379
    depends_on:
      - redis

  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    environment:
     - REDIS_HOST=envoy_proxy_1
     - REDIS_PORT=6379
    volumes:
      - ./worker:/code
    depends_on:
      - proxy
